### PR TITLE
Document top-level APIs

### PR DESCRIPTION
**Pull request by dawran6**
This PR addresses #84.
Add a documentation test to ensure top-level APIs have docs.

This is the documentation progress:

`coast.responses`
* - [x] ok
* - [x] bad-request
* - [x] not-found
* - [x] unauthorized
* - [x] server-error
* - [x] redirect
* - [x] flash

`coast.error`
* - [x] raise
* - [x] rescue

`coast.db`
* - [x] q
* - [x]    pull
* - [x]    transact
* - [x]    delete
* - [x]    insert
* - [x]    update
* - [x]    first!
* - [x]    pluck
* - [x]    fetch
* - [x]    execute!
* - [x]    find-by
* - [x]    transaction

`coast.db.connection`
* - [x]    connection

`coast.validation`
* - [x]    validate

`coast.components`
* - [x]    csrf
* - [x]    form
* - [x]    js
* - [x]    css

`coast.router`
* - [x]    routes
* - [x]    wrap-routes
* - [x]    prefix-routes
* - [x]    with
* - [x]    with-prefix

`coast.middleware`
* - [x]    wrap-with-layout
* - [x]    with-layout
* - [x]    wrap-layout
* - [x]    site-routes
* - [x]    site
* - [x]    api-routes
* - [x]    api
* - [x]    content-type?

`coast.theta`
* - [x]    server
* - [x]    app
* - [x]    url-for
* - [x]    action-for
* - [x]    redirect-to
* - [x]    form-for

`coast.env`
* - [x]    env

`coast.jobs`
* - [x]    queue

`coast.utils`
* - [x]    uuid
* - [x]    intern-var
* - [x]    xhr?

`coast.time2`
* - [x]    now
* - [x]    datetime
* - [x]    instant
* - [x]    strftime

`hiccup2.core`
* - [x]    raw
* - [x]    html

### CODE REVIEW

**Comment by dawran6** [comment]
I hope the changes I made for the code alignment aren't too big of an issue to you @swlkr. I had my editor's auto formatting turned on and it was pretty aggressive.

I can also help with porting the docs to other repos or the `next` branch.

Thanks.

**Comment by swlkr** [comment]
No worries about the formatting, I'm not really dogmatic about it. Which formatter do you use? I don't think I even use one 😅

**Comment by swlkr** [comment]
I think this looks good :shipit:

**Comment by dawran6** [comment]
Thanks for reviewing! Lately, I adopted the [aggressive-indent-mode](https://emacsredux.com/blog/2016/02/07/auto-indent-your-code-with-aggressive-indent-mode/) in my spacemacs and it truly has been aggressive since. The mode aligns the function arguments on every keystroke so I wasn't totally aware until I commit it.

**Pull request merged**
